# Version of docker-compose
version: '3'

services:
  phoenix:
    image: localhost:5000/kawapi-phoenix:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST: $HOST
        PORT: $PORT
        MIX_ENV: prod
        DATABASE_URL: $DATABASE_URL
        SECRET_KEY_BASE: $SECRET_KEY_BASE
        SMTP_USERNAME: $SMTP_USERNAME
        SMTP_PASSWORD: $SMTP_PASSWORD
    ports:
      - "4000:4000"
  phoenix-db:
    image: localhost:5000/kawapi-phoenix-psql:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
          HOST: $HOST
          PORT: $PORT
          MIX_ENV: prod
          SECRET_KEY_BASE: $SECRET_KEY_BASE
          SMTP_USERNAME: $SMTP_USERNAME
          SMTP_PASSWORD: $SMTP_PASSWORD
          DATABASE_URL: $DATABASE_URL
    ports:
      - "$PORT:$PORT"
    depends_on:
      - db
  db:
    # mix ecto.setup
    # createdb --host localhost -p 5433 -U postgres basic
    image: postgres:9.6
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
      PGDATA: $PGDATA
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  pgdata: