# Version of docker-compose
version: '3'

services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST: $HOST
        PORT: $PORT
        MIX_ENV: prod
        DATABASE_URL: $DATABASE_URL
        SECRET_KEY_BASE: $SECRET_KEY_BASE
    ports:
      - "4000:4000"
  phoenix-db:
    build:
      context: .
      dockerfile: Dockerfile.pg
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/basic
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: basic
      PGPORT: 5432
      PGHOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: