# Version of docker-compose
version: '3'

services:
  phoenix:
    image: yodascholtz/kawapi-phoenix:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST: $HOST
        PORT: $PORT
        MIX_ENV: prod
        DATABASE_URL: $DATABASE_URL
        SECRET_KEY_BASE: $SECRET_KEY_BASE
    ports:
      - "4000:4000"
  phoenix-db:
    build:
      context: .
      dockerfile: Dockerfile.pg
    environment:
      DATABASE_URL: $DATABASE_URL
      PGUSER: $PGUSER
      PGPASSWORD: $PGPASSWORD
      PGDATABASE: $PGDATABASE
      PGPORT: $PGPORT
      PGHOST: $PGHOST
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
      PGDATA: $PGDATA
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: